### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by emxsys** [WorldWindEarth/explorer#128]
Issue: There are http links this the Explorer code base that need to be converted to https to avoid mixed content violations in the browser when using secure connections.

**Comment by nicolasvila** [comment]
Hi Bruce.
I confirm an issue when adding a HTTPS based WMS service (requests are sent with http:// instead of https://)
Usually I'm setting up a default/empty HTTP virtualhost on Nginx  server redirecting permanently all the requests to https. Seems that WWE does not follow the redirection, despite I can see the tiles images in the Chrome network tab.

**Comment by emxsys** [comment]
Changed http links to https.
Changed project setting to not enforce https.
